/**
 * GENERATED by `npm run build:images`. Do not edit by hand.
 *
 * It records what is actually on disk in public/images/, so that a component
 * never has to guess and never renders a broken <img>. Checked in on purpose:
 * the site must build correctly from a fresh clone without running the image
 * pipeline first.
 */

export const GENERATED_PHOTOS: readonly string[] = [];

export const GENERATED_LOGO = {
  present: false,
  cutout: false,
} as const;
